version: '3.8'

networks:
  backend:
    external: false
    name: backend
services:
  dbmysql:
    networks:
      - backend
    image: mysql:5.7.12
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=geocoding
    
  # adminer:
  #   networks:
  #     - backend
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  
  